Ensure .env variables are defined

diff --git a/mongodb-replica-set/Makefile b/mongodb-replica-set/Makefile
--- a/mongodb-replica-set/Makefile
+++ b/mongodb-replica-set/Makefile
@@ -16,9 +16,14 @@ config:
 # docker stack-up
 .PHONY: stack-up
 stack-up:
-	./create-key-file.sh -f -o deploy/mongodb.keyfile
-	docker stack deploy --with-registry-auth -c docker-stack.yml $(project)
-	docker exec -it $$(docker ps --filter name=mongors_db-mongo1 --format {{.ID}}) /root/init-replica-set.sh
+	@if [ "$$MY_MONOGO_REPLICA_SET_NAME" != "" ] && [ "$$MY_INITDB_ROOT_USERNAME" != "" ] && [ "$$MY_INITDB_ROOT_PASSWORD" != "" ]; then \
+		./create-key-file.sh -f -o deploy/mongodb.keyfile && \
+		docker stack deploy --with-registry-auth -c docker-stack.yml $(project) && \
+		docker exec -it $$(docker ps --filter name=mongors_db-mongo1 --format {{.ID}}) /root/init-replica-set.sh ; \
+	else \
+		echo "Error: .env variables is not set yet! Please source .env properly." ; \
+		exit 1 ; \
+	fi
 
 # docker stack down
 .PHONY: stack-down
